### ISSUE TITLE
study 내용 메모 방법 추천드립니다 :)

### ISSUE THREAD

**Issue by alex-gibeom** [HUNSIKLEE/study#1]
안녕하세요!
study 메모를 txt 파일로 작성하시는 거 같아서 추천드리고 싶어서 이슈 남깁니다
github에서도 잘 지원해주는 마크다운(markdown) 방식으로 작성할 수 있는 md파일을 사용하여 메모를 해보시는건 어떨까요?
파일 생성할때 파일확장자를 .md로 지정해주시면 됩니다 :)

<br>

#### 마크다운을 이용한 메모 예시
- 제가 마크다운을 이용해서 공부한 내용을 메모한 글을 참고 드립니다
- [변수와 메서드, 그 속으로](https://github.com/All-Rounder-Storage/programmers_knowledge_storage/blob/main/Backend/Java/Java%EC%9D%98%20%EC%A0%95%EC%84%9D/%EB%B3%80%EC%88%98%EC%99%80%20%EB%A9%94%EC%84%9C%EB%93%9C%2C%20%EA%B7%B8%20%EC%86%8D%EC%9C%BC%EB%A1%9C.md)

<br>

#### 마크다운 사용법을 잘 설명해주는 영상 추천드립니다
- [드림코딩 엘리 - 마크다운(Markdown) 6분 순삭 정리](https://youtu.be/kMEb_BzyUqk)

**Comment by HUNSIKLEE** [comment]
감사합니다!!!!!!!
